# fly.toml app configuration file generated for clone-youtube on 2023-04-20T16:10:50+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "clone-youtube"
primary_region = "nrt"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
